### ISSUE TITLE
Can't get proper result from the test data

### ISSUE THREAD

**Issue by az508** [computer-vision/takahashi2012cvpr#1]
Hi:

I've tried the new version with the test data, but can't get correct result. The reprojection error is extremely large (about 8000 pixel) and the estimated parameters looks strange

`R =

   -0.2894    0.3261    0.8999
   -0.7342   -0.6789    0.0099
    0.6142   -0.6578    0.4359

T =

  1.0e+132 *

   -0.3988
   -0.0349
   -1.2250

n1 =

   -0.2983
   -0.0369
   -0.9538

n2 =

   -0.3227
   -0.0536
   -0.9450

n3 =

   -0.3268
   -0.0674
   -0.9427

d1 =

 -6.4316e+131

d2 =

 -6.4322e+131

d3 =

 -6.4308e+131`

Matlab showed some message like 
`Warning: Matrix is close to singular or badly scaled. Results may be inaccurate. RCOND =  2.042577e-26. 
> In gauss_newton at 34
  In optimize_betas_gauss_newton at 29
  In efficient_pnp_gauss at 216
  In tnm at 60
  In demo at 53 ` 

Do you have any idea?

Best

**Comment by qtarou** [comment]
Hi. Thank you for the comment.

I'm sorry. I have fixed the bug. Please get updated code and try it.
(I replaced the efficient_pnp_gauss() function to efficient_pnp() in tnm.m.
Notice that the estimation of 3D point (i.e. EPnP) are not our contributions and you can replace this function with other  algorithm for more robust estimation.)

Best

**Comment by az508** [comment]
Thank you for the reply. I get correct result now.

Best
